### ISSUE TITLE
Turn mapping on / off 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#227] opened 2022-08-09 22:01 UTC
For very large planning areas (ex. entire provinces), it would be good if the user can specify if the layers and solutions should generate `RasterLayers` or not. If not, layers wont display and `RasterLayers` would not generate from the attribute table.  

![image](https://user-images.githubusercontent.com/29556279/183766535-b50d4127-c01f-44e1-82a8-0f50f0839af4.png)

Currently there is a `hidden` parameter for `new_feature` , `new_weight` and `new_include`. When set to `TRUE`, the layer is never displayed. <del> However, the `RasterLayer` for that feature is still held in-memory when the `Dataset` object is created. </del> 

This change would allow users to add very large planning areas to Where To Work and not get slowed down by the tool generating rasters from the attribute table and of course hitting a wall when mapping to leaflet.

**Comment by ricschuster** [comment] 2022-08-09 23:22
Thanks Dan!
If at all possible, this would also great to work with `polygon` data.

**Comment by DanWismer** [comment] 2022-08-10 16:30
The `Variable` class has a method `get_data()` which calls the `get_index()` method on the `Dataset` object. The `get_index` method is where `sf` or `RasterLayer` objects are generated referencing the attribute table. For `RasterLayer` objects, the `raster::SetValues` is used, having the `spatial.tif` as the template. The `get_data()` method is called when the `render(x, id, zindex, visible)` is called. 

The class `Theme` , `Weight` and `Include` have a `render_on_map` method which calls the `render` method from the `Variable` class. However, if the feature is `hidden`, `render_on_map` never gets called, which means the attribute column associated with that feature is never turned into an `sf` or `RasterLayer` object and held in-memory. 

If I have read the code correctly, specifying `hidden` as `TRUE` does not create a `RasterLayer` or `sf` object in-memory and does not map to leaflet. 

... I need to look into how the legend is created and when the spatial statistics are generated to populate the sliders on the right-side bar (how much of a feature is within the includes). Stay tuned.

**Comment by DanWismer** [comment] 2022-08-10 17:04
After further review, I see that the `get_index` method which builds `RasterLayer` or `sf` objects is also called on the `new_variable_from_auto` constructor.

**Comment by DanWismer** [comment] 2022-08-11 15:32
`server_import_builtin_data.R` and `server_import_manual_data.R` call the function `read_project`.  `read_project` imports the data and builds variables using the `new_variable_from_auto`. `new_variable_from_auto` calls `get_index` from the `new_dataset` which converts attribute columns to `RasterLayer` or `sf`.

The `new_variable_from_auto` looks to only need a `RasterLayer` or `sf` to calculate the `spatial_data_statistics`. For example, raster data uses the `raster::cellStats` to calculate `min_value` and `max_value` for continuous data.

With that all being said, could we not just calculate the stats using the attribute table? That way, we can avoid converting each column into a layer held in-memory.

@jeffreyhanson , I am wondering if we can review all this in our next session.

**Comment by DanWismer** [comment] 2022-08-12 17:30
I have added a new `hidden` parameter to  `new_variable_from_auto` which set to `yes` uses the attribute table to calculate the statistics for the legend instead of building `Raster` or `sf` layers. Also, by setting features, weights and includes to `hidden` I get way better performance once the BC pilot (large project I am using for testing) project is uploaded:

![image](https://user-images.githubusercontent.com/29556279/184412149-ed8d3b8d-6718-493e-a7e5-3685521e9c57.png)

**Comment by DanWismer** [comment] 2022-08-15 15:29
Posting a question so I don't forget:

When a `Variable` object is created, it brings with it the entire attribute table. That can be a lot of full attribute table copies, especially when there are a lot of variables. I am wondering if only the specific column of the attribute table is needed?

**Comment by jeffreyhanson** [comment] 2022-08-15 21:46
Nah, the variable object doesn't actually store a full copy of the data. This is because the data is stored in a Dataset (R6) object -- that the Variable object refers to -- and R6 objects have copy-on-reference semantics. See https://adv-r.hadley.nz/r6.html

**Comment by DanWismer** [comment] 2022-08-16 16:14
Thanks Jeff.

I have been playing around with the `server_import_data.R` script and found that I can populate `app_data$mm` with an empty `new_map_manager(list = list())`. This creates a blank TOC. 

After messing around with the code, I am hitting this new error with the `future` package. It is telling me that the project I am running priortizatrions on exceeds the maximum allowed size of 500 MiB. The three largest globals are ‘curr_theme_data’ (1.46 GiB of class ‘S4’), ‘curr_weight_data’ (35.25 MiB of class ‘S4’) and ‘curr_boundary_data’ (8.47 MiB of class ‘S4’)

I wasn't hitting this error before and I can't find what I changed that would have triggered that ...

**Comment by jeffreyhanson** [comment] 2022-08-16 20:40
Hmm, I'm sorry, nothing comes to mind immediately. I'd suggest determining if the issue is being caused before (1) a large amount of data is being transferred to the worker process for async processing (which is where future comes in), (2) if the processing done on the worker process during async is using up >500 MB RAM, or (3) the results being sent from the worker process back to the main process is exceeding 500 MB RAM (i.e., this list here: https://github.com/NCC-CNC/wheretowork/blob/master/R/server_generate_new_solution.R#L179-L183). How does that sound?

**Comment by jeffreyhanson** [comment] 2022-08-16 20:43
Also, future works by automatically working out objects in the given environment should be sent to the worker process and then sending out the data to the worker. So, it might be possible that it's sending a bunch of extra stuff that's not actually needed? So if you can confirm (1) is causing the problem, then it might be worth seeing if you can manually specify which objects should be sent to the worker process. Dunno if that will work - just an idea?

**Comment by DanWismer** [comment] 2022-08-16 21:51
Thanks Jeff, I can confirm that it is scenario 1 (a large amount of data is being transferred). It fails right when it hits the `min_set_result` function

**Comment by DanWismer** [comment] 2022-08-16 22:02
Interesting, I put a `browser()` statement for when the `input$newSolutionPane_settings_start_button` gets triggered. On the master branch,  `object.size(curr_theme_data)` is 0.362402152 GB. And on my mapping on / off branch,  `object.size(curr_theme_data)` is 1.568400808 GB. I am wondering how that has ballooned up so much ...

**Comment by DanWismer** [comment] 2022-08-17 15:21
I put another `browser()` statement in `server_import_manual_data.R` and inspected the output of the `read_project` function (a list of themes, weights and includes) and the `app_data`  environment after `import_data` function is executed. What is interesting is that the `object.size(x$themes)` is only 1816 bytes, but the `object.size(app_data$theme_data)` is 1.5 GB. 

Trying to figure out why when `x` is imported into the `app_data` environment, theme data grows in size ....

**Comment by DanWismer** [comment] 2022-08-17 17:36
ok, I see why `app_data$theme_data` is bigger then `x$themes`. Thats becuase `app_data$theme_data` is a `dgcMatrix`  (generated by the `get_theme_data` method on the `SolutionSettings` class) and `x$themes` is a list from `read_project` function

**Comment by DanWismer** [comment] 2022-08-17 19:54
... finally figured out what was going on. I made some changes to the `new_variable_from_auto` constructor and was converting the `index` value to a numeric which was causing the `Variable` class to grow in size.  Long story short, running a prioritization  works again on my mapping on/off branch. 

These are just some notes so I remember for later:
I need to read up on what copy-on reference is. I am still foggy with the concept. Looking at my R Studio memory icon, a fresh Where to Work session I start with 167 MiB. When I `run_dev` and Where To Work initializes, my memory goes to 636 MiB. When I import the BC project data, my memory goes to 4.5 GiB, then drops back down to 1.63 GiB. Long story short, I am unsure if reading in the attribute table to create variables is a better approach then reading in the dataset as an `sf` or `raster`

**Comment by DanWismer** [comment] 2022-08-17 22:11
@ricschuster 

In my dev environment, I have it that you can check if you want to hide (disable all the layers):
![image](https://user-images.githubusercontent.com/29556279/185251817-64d495c1-b1a0-49b6-8c4f-0e8ec83eab12.png)

This overwrites the `hidden` attribute on the `new_theme`, `new_weight` and `new_include` constructors to `TRUE`
![image](https://user-images.githubusercontent.com/29556279/185251993-b72246cd-6d0c-48f0-8d83-9b1ec39975eb.png)

What are your thoughts on 3 check boxes to control if the user wants to hide themes and/or weights and/or includes. Or is one check box that hides all them make more sense?

**Comment by ricschuster** [comment] 2022-08-18 12:47
Thanks Dan! My preference would be one check box. 
Do you think having 3 would be useful? 

Question about solutions: is there a way to set those to hidden (or at least turned off)  as well? 
I'm thinking primarily about projects with large numbers of polygons that would take ages to map.

**Comment by DanWismer** [comment] 2022-08-18 14:07
1 check box for turning off themes, weights and includes works for me. Having 3 provides more flexibility (say you wanted to view the includes but have themes and weights off), but I can make that change if there ends up being a user need.

And yes, I was thinking the same. I will add a new check box where the user can specify if they want to hide the solution from the map. For the BC example, showing the solution with everything else turned off has good responsiveness. But I can see that not being the case as you mentioned with polygons and also if the planning units were smaller

**Comment by ricschuster** [comment] 2022-08-18 19:36
1 check box sounds great. Thanks!

Would you want to add a separate check box for mapping solutions now or add that functionality to the 1 check box? 1 check box would make for a simpler user experience. If you use e.g. "layer mapping on/off" that could cover things.

**Comment by DanWismer** [comment] 2022-08-18 20:13
The main reason for a sperate check box is that for some projects (take BC for example), having the site selection display on the map works well.   

![image](https://user-images.githubusercontent.com/29556279/185484507-fd675da0-eb63-40a7-a6b6-530cbfa31630.png)
![image](https://user-images.githubusercontent.com/29556279/185484960-db2b0eef-2d20-4759-b0d0-47741c41d498.png)

And for the projects where it doesn't, then the user can turn the mapped solution off (I suppose the user won't know until they try it out first)
![image](https://user-images.githubusercontent.com/29556279/185485239-574ab5fe-e8b0-4a05-bcc6-ea10ef0d7c0b.png)
![image](https://user-images.githubusercontent.com/29556279/185485670-71fcc81d-a84f-4471-a247-d61478d27619.png)

However, now that I think about it. It may be best to have mapping the solution on/off nested in the settings:
![image](https://user-images.githubusercontent.com/29556279/185485905-c89c5f71-1f29-466d-b5a0-662a824295ba.png)

That way the user can change this on and off need be within the same session

**Comment by ricschuster** [comment] 2022-08-18 21:26
Nested in the settings sounds good. What if we have a setting to turn results layers off (meaning don't display) instead of not making them available to map (i.e. complete off)? Would that work or still cause issues with say polygon layers?

**Comment by DanWismer** [comment] 2022-08-19 16:48
If a layer is set to visible == FALSE, it still gets rendered to the map and held in-memory which will bog down performance. 

What I ended up doing here is removing the "Hide solution" check box at import and moved that functionality under the "Settings" tab. That way you can change this option within the session:

Hide:
![image](https://user-images.githubusercontent.com/29556279/185667353-2881130f-2972-4b24-8ab4-16ed21c3bf59.png)
![image](https://user-images.githubusercontent.com/29556279/185667446-85b96dc2-9706-4338-913d-0ab477252e52.png)

Show:
![image](https://user-images.githubusercontent.com/29556279/185667580-c1ec2037-7403-4ff5-9ba1-a56f18323236.png)
![image](https://user-images.githubusercontent.com/29556279/185667664-6e521d68-e32f-4285-a5a0-b0033fe4729d.png)

**Comment by ricschuster** [comment] 2022-08-19 18:11
Awesome! Thanks Dan!

**Closed** 2022-08-26 14:08 UTC
