### ISSUE TITLE
text overlap in weights when examining solution results

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/wheretowork#200] opened 2022-03-18 16:04 UTC
![ncc carleton ca_app_wheretowork_advanced_sp_hide_navbar=true (1)](https://user-images.githubusercontent.com/33939350/159039085-25bc9645-62b3-4c8d-918f-d1937042a2d8.png)
![ncc carleton ca_app_wheretowork_advanced_sp_hide_navbar=true](https://user-images.githubusercontent.com/33939350/159039181-daca94ea-ac5c-493a-85bd-0ab406ff6abd.png)

**Comment by DanWismer** [comment] 2022-04-01 16:01
Interesting, thought we tackled this one (issue #177). I am testing the production app and labels are wrapping by design (built-in project). However, I am wondering if labels are not wrapping when the user uploads their own project?   

![image](https://user-images.githubusercontent.com/29556279/161299749-1d0962e8-eaf8-406e-922e-9369ad47d98a.png)

**Comment by jeffreyhanson** [comment] 2022-04-01 20:45
@DanWismer, Hmm, I wouldn't expect the data upload method to have an effect. I wonder if it's something specific for underscores or a maybe web browser differences?

@josephrbennett, do you remember which web browser you were using when you encountered this issue?

**Comment by jeffreyhanson** [comment] 2022-05-01 22:10
I think this has been fixed now, so I'll close it. Since the Docker builds were failing for a while, this meant that even though we fixed the issue in the source code - this upate wasn't making it to the production server. But now that we've fixed the Docker builds, the version on the production server has the fix. Please feel free to re-open this issue if this issue is encountered again.

**Closed by jeffreyhanson** 2022-05-01 22:10 UTC
Labels: bug, high priority
