### ISSUE TITLE
YAML Feature name with period causes upload error

### ISSUE THREAD

**Issue by JCLaurence** [NCC-CNC/wheretowork#179] opened 2021-12-07 22:29 UTC
Uploading a Yaml config file containing a feature with the name "Sporobolus rigidus var. magnus"    (quotes are added by me)  generates an error during the upload.  Removing the period in the name and re-uploading generates no error.  Looks like the "." causes issues.  I am interested to know if there are other characters that might also cause issues.

**Comment by jeffreyhanson** [comment] 2021-12-08 01:59
Thanks for reporting this! Could you please post the YAML file so I can reproduce this on my computer? I wouldn't have expected the presence of a `"."` in a string to cause issues. I would expect that many users will probably use a `"."` in feature names, so I think this is a bug that should be fixed.

**Comment by JCLaurence** [comment] 2021-12-08 13:24
[WTW_CONFIG.zip](https://github.com/NCC-CNC/wheretowork/files/7676264/WTW_CONFIG.zip)

**Comment by JCLaurence** [comment] 2021-12-08 13:24
# wheretowork project import log

## Summary

Failed to import the following Themes: "Endemics"

## Details

### Endemics

Error : isFALSE(x = grepl(".", name, fixed = TRUE)) is not TRUE

**Comment by JCLaurence** [comment] 2021-12-08 13:25
I agree - we'll probably want to include various non-letter characters in our theme names so it would be good to identify the source of the error

**Comment by jeffreyhanson** [comment] 2022-02-14 21:15
I'm looking into this issue now. It turns out that the code responsible for throwing the error was actually put there deliberately by me to ensure valid names (https://github.com/NCC-CNC/wheretowork/commit/1a7f0d0857c32d7ec1951542aa0e3155df0fe1f5). In a previous issue (https://github.com/NCC-CNC/wheretowork/issues/145), @ricschuster determined that the R package for reading/writing files would crash his computer when attempting to write YAML files with a period in the strings. It seems that the yaml R package has since been updated, so I'll see if the new version has fixed this.

**Closed** 2022-02-15 02:46 UTC
Labels: bug, high priority

**Comment by jeffreyhanson** [comment] 2022-02-15 03:03
@JCLaurence, I've updated the app so that periods are now ok in the theme, feature, include, and weight names. Please feel free to reopen this issue if you encounter this issue again.

**Comment by JCLaurence** [comment] 2022-02-15 03:08
Hi Jeff!  Hopefully by adding this comment I'm not reopening the issue...  Can you let me know what characters are either allowable or not allowable (whichever is easiest) in names?  Knowing that periods are good now is great, but it would be better for me to have a list of bad characters so I can avoid allowing them at my end.

**Comment by jeffreyhanson** [comment] 2022-02-15 04:11
Nah, it'll only reopen the issue if you click one of the buttons that says reopen.

Yeah, my understanding is that all ascii characters should be fine (e.g. any character on the QWERTY keyboard). For full list, [see here](https://www.w3schools.com/charsets/ref_html_ascii.asp#:~:text=ASCII%20is%20a%207%2Dbit,are%20all%20based%20on%20ASCII).
