### ISSUE TITLE
change layer colours in the table of content

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#132] opened 2021-08-12 18:34 UTC

**Comment by jeffreyhanson** [comment] 2021-08-12 21:57
I really like this idea! I think it would make the app a lot more interactive, and help facilitate more customization/exploration of data. Unfortunately, this would also be a lot of work. Since this would require extending some of the custom JS/HTML widgets in the app, I can't simply drop in pre-made widgets from other R packages to implement this functionality -- meaning that I would have to write a bunch of JS, HTML, and CSS to get this working. As such, I think this would take about a month of solid work to get working properly - so I don't think this is something I can get working in the near future. Can we leave this issue open for now, and I'll see if I can revisit it if I get more time later?

**Comment by ricschuster** [comment] 2021-08-13 00:44
No worries at all. I just wanted to provide the feedback from people here. What do you think about labels that indicate that issues aren't urgent at all? We could do something like 'staff suggestions' or something similar? It would be good to capture them, but also indicated that they are comments and not requests at this point. Would be good to collect them and eventually have discussions about feasibility and priority of issues. Do you have ideas about how to do that?

**Comment by jeffreyhanson** [comment] 2021-08-13 00:47
Ok - sounds good. Yeah, I like the idea of adding a label to identify stuff we can do later. I've seen a "sometime" label used in other GitHub repo's to denote possible enhancements that could be potentially be added in the future - what do you tihnk?

**Comment by ricschuster** [comment] 2021-08-13 02:21
sometime it is. Added the label.

**Comment by jeffreyhanson** [comment] 2021-08-13 02:22
Great-  thanks! I'll tag other issues with this label too. Also - I'll change the color because the "high priority" label is black - which might get a bit confusing.

**Comment by ricschuster** [comment] 2021-08-13 02:25
Sorry about the color. I'm using the dark theme where the contrast is fine.

**Comment by jeffreyhanson** [comment] 2021-08-13 02:31
Ah - no worries! Is the new label color ok on the dark theme?

**Comment by jeffreyhanson** [comment] 2021-09-07 03:36
Closing this because it's a duplicate of #154

**Closed by jeffreyhanson** 2021-09-07 03:36 UTC
Labels: enhancement, sometime
