### ISSUE TITLE
solution input values and params .yaml config upload option

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#278] opened 2023-01-17 17:11 UTC
This will automatically enable toggles, set values and parameters stored in the `_config.yaml` . The `_config.yaml` is populated on solution download (issue #277)

**Comment by DanWismer** [comment] 2023-02-02 16:42
@jeffreyhanson 

I made some progress with this and actually got it to work for includes: 

1.  user uploads .yaml config (under settings)
2. the .yaml config is passed as text from the `solutionSettings` widget (actually got this to work using [JS](https://jsfiddle.net/vgepw79u/) ) which populates the `fileinput` attribute on the `Parameter` class
3. read-in the `fileinput` string as a list with `yamal::yamal.load` with a new method on the class `solutionSetting`
4. new `update_settings()` method on the `solutionSetting` class where I `lapply` over the user **config list** and use the `set_setting` method to update the **status** (if toggle is on or off for includes) 
5. Finally, update the UI using the [updateSolutionSettings](https://ncc-cnc.github.io/wheretowork/reference/updateSolutionSettings.html) in the `server_update_solution_settings.R`

For themes, I am struggling with how I can access if the user has toggled the **group** or **single** tab. For example, the `.yaml` that now downloads  with the solution documents all the individual feature settings. However, I also need to access the **group** theme info, such as if it is toggled on and what the **group goal** is.  

Wondering if you have any ideas on this? I don't see where those parameters are stored ....

**Comment by jeffreyhanson** [comment] 2023-02-02 20:13
Brilliant! Hmm, I don't think the Feature class stores information on whether the user has toggled the group or the single tab. So, maybe you could set it using a rule of thumb? E.g., if all of the features within a theme are assigned to the same goal, then use the single table. Otherwise, if different features within a given theme are assigned different goals, then use the group tab? However, one tricky edge case would be if the user is on beginner mode and wants to upload a solution with different goals per feature in the same theme (which could only be generated a under advanced mode) -- so maybe you'd need to do some data validation to ensure that a settings file is compatible with the app mode?

**Comment by jeffreyhanson** [comment] 2023-02-02 20:16
Also, to manually change the mode, you might need to update `updateSolutionSettings` so that you can specify single/group tab should be shown. This would probably require some updates to the JS code as well.

**Comment by jeffreyhanson** [comment] 2023-02-02 20:16
Does that help?

**Comment by DanWismer** [comment] 2023-02-02 22:29
Thanks @jeffreyhanson , yea it does help. I need to keep throwing stuff at the wall to see if I can get it to stick. This feature is a tricky one!

On another note, I am stuck in an infinite loop when I update weight factors.  I think when I update the factor, it goes to the client, then the slider gets updated on the client and goes back to the server? And on and on it goes. This behavior is not happening when I update the status (toggle switches)

https://github.com/NCC-CNC/wheretowork/blob/e8088d4b07eea38b91e57e198ae106308e032dac/R/server_update_solution_settings.R#L44

Wondering if you have any ideas on this?

**Comment by DanWismer** [comment] 2023-02-02 22:57
ah I figured it out, I needed to nest all those `updateSolutionSettings` inside: https://github.com/NCC-CNC/wheretowork/blob/e8088d4b07eea38b91e57e198ae106308e032dac/R/server_update_solution_settings.R#L26-L28

**Comment by DanWismer** [comment] 2023-02-02 23:55
On another note, with my current code, I can get `solutionSettings(app_data$ss)` to render the updated settings in my console:
![image](https://user-images.githubusercontent.com/29556279/216477054-52ef702c-b774-4291-af90-5874492034f4.png)

I was thinking maybe I can re-render the entire solution setting all at once, without executing a `lapply` over each feature followed by `updateSolutionSetting`

However, when I try this, it doessn't update the UI
```   if(input$newSolutionPane_settings$setting == "fileinput") {
     app_data$ss$set_user_settings()
     app_data$ss$update_settings()
     # render the updated solution settings
     output$newSolutionPane_settings <- renderSolutionSettings(solutionSettings(app_data$ss))
```

**Comment by DanWismer** [comment] 2023-02-03 15:26
I am now wondering if I could implement a [Proxy Function](https://book.javascript-for-r.com/shiny-widgets.html#shiny-widgets-proxy)

**Comment by DanWismer** [comment] 2023-02-03 19:31
> Also, to manually change the mode, you might need to update `updateSolutionSettings` so that you can specify single/group tab should be shown. This would probably require some updates to the JS code as well.

I think you built this already! [Update solution settings widget](https://ncc-cnc.github.io/wheretowork/reference/updateSolutionSettings.html)

 
![image](https://user-images.githubusercontent.com/29556279/216691174-4188b65e-b21e-4c95-82e0-be27d75f9b27.png)

**Comment by jeffreyhanson** [comment] 2023-02-05 20:22
Ah - you're right! Lol sorry, I forgot about that.

**Comment by jeffreyhanson** [comment] 2023-02-05 20:24
A proxy function could work - but I think that's a different framework (e.g. compared with the htmlwidgets framework) for passing data/info between the server and the client. I would suggest sticking with htmlwidgets if possible to keep things consistent.

**Comment by DanWismer** [comment] 2023-02-06 16:52
@jeffreyhanson 

Do you remember this? https://github.com/NCC-CNC/wheretowork/blob/100895f32767d31f1d8d59c5d4656a8485debcfc/inst/htmlwidgets/lib/solutionSettings-1.0.0/IncludeSetting-class.js#L102-L109

I believe it is designed to enable / disable the styles of the label. However, I had to re-write it to this for it to work with the update function.

``` 
 updateStatus(value) {
    this.status_el.checked = value;
    if (value) {
      this.name_el.removeAttribute("disabled");
    } else {
      this.name_el.setAttribute("disabled", "");
    }
  }
````
This is giving me an empty NodeList, 
https://github.com/NCC-CNC/wheretowork/blob/100895f32767d31f1d8d59c5d4656a8485debcfc/inst/htmlwidgets/lib/solutionSettings-1.0.0/IncludeSetting-class.js#L102-L103
... but I want to confirm that this is not required for other parts of the update ... so far nothing has broken ...

**Comment by jeffreyhanson** [comment] 2023-02-06 20:50
Yeah that's exactly correct! The code was intended to update the styling for the element when the status was changed. Since it's the include setting, it should update the label (so that its greyed out) and the slider (so that its toggled off). Does the app have that behavior with the new code?

**Comment by DanWismer** [comment] 2023-02-07 18:41
Made some good progress on this:

https://user-images.githubusercontent.com/29556279/217336356-2010baf0-3427-4db5-a0fa-0acc91ab852a.mp4

**Comment by DanWismer** [comment] 2023-02-07 18:50
> Yeah that's exactly correct! The code was intended to update the styling for the element when the status was changed. Since it's the include setting, it should update the label (so that its greyed out) and the slider (so that its toggled off). Does the app have that behavior with the new code?
> 
> EDIT: Yeah, changing this should only affect the include stuff and not any other parts of the app.

I found that for weights and themes, I needed to keep:
``` 
    let els = this.el.querySelectorAll(
        ".disable-if-inactive, .disable-if-inactive.icon i");
    if (value) {
      els.forEach((x) => x.removeAttribute("disabled"));
    } else {
      els.forEach((x) => x.setAttribute("disabled", ""));
    }
````
However for includes, excludes and sinlgeThemeSettings, that code above didnt seem to work and I had to explicitly remove and set attributes. ex.
````
 if (value) {
        this.name_el.removeAttribute("disabled");
        this.goal_el.removeAttribute("disabled");
        this.goal_label_el.removeAttribute("disabled");
        this.goal_symbol_el.removeAttribute("disabled");
        this.reset_el.removeAttribute("disabled");
        this.goal_el.noUiSlider.set(this.previous_goal);
      } else {
        this.name_el.setAttribute("disabled");
        this.goal_el.setAttribute("disabled");
        this.goal_label_el.setAttribute("disabled");
        this.goal_symbol_el.setAttribute("disabled");        
        this.reset_el.setAttribute("disabled");
        this.previous_goal = this.goal_el.noUiSlider.get();
        this.goal_el.noUiSlider.set(this.limit);
      }
````
Not sure why though ...

**Comment by jeffreyhanson** [comment] 2023-02-07 20:15
Brilliant! The demo vid looks like its working perfectly!

**Closed** 2023-02-13 20:14 UTC
Labels: enhancement

**Comment by DanWismer** [comment] 2023-02-13 20:18
PR #285

**Comment by DanWismer** [comment] 2023-02-13 20:54
thinking about changing the label name to `Update solution settings` instead of `Input configurations`
